import type { ContentBlock } from './scene';

export const INTRO_CONTENT: ContentBlock[] = [
  {
    id: 'hook-heading',
    chapterId: 'hook',
    sceneId: 'teaser-cross-section',
    heading: 'What happens when you ask a coding agent to build something?',
    body: 'You type a plain-English request — "build me a landing page" — and press enter. The model begins. But what actually happens between that request and the finished page? The answer is not "the model figures it out." The answer is a system — a harness — that turns model intelligence into real, verifiable work.',
    lensMode: 'product',
  },
  {
    id: 'hook-body',
    chapterId: 'hook',
    sceneId: 'teaser-cross-section',
    heading: 'The mental model shift',
    body: 'Most of us imagine a coding agent as a chatbot with better prose. A smart text-in, smart-text-out machine. That model is wrong. A coding agent is a system that reasons, acts through tools, observes results, and continues — not a single response, but a work loop that runs until the job is done.',
    lensMode: 'product',
  },
  {
    id: 'illusion-heading',
    chapterId: 'illusion-break',
    sceneId: 'model-only-misconception',
    heading: 'The model alone cannot do this job',
    body: 'A language model on its own can produce text. It can describe a landing page. It can write HTML. But it cannot open a file, read your existing codebase, run a test, or check whether its output actually works. The model is a reasoning engine. Without a harness around it, it is blind, handless, and stateless.',
    lensMode: 'product',
  },
  {
    id: 'illusion-contrast',
    chapterId: 'illusion-break',
    sceneId: 'model-only-misconception',
    heading: 'Model-only vs. harnessed agent',
    body: 'Without a harness, every request starts from scratch. The model cannot persist state, browse project structure, run commands, or validate outcomes. A harness changes this: it gives the model eyes (file reads), hands (tool execution), memory (session state), and boundaries (permissions). The difference is the difference between a brilliant advisor and a capable colleague.',
    lensMode: 'product',
  },
  {
    id: 'harness-heading',
    chapterId: 'harness-reveal',
    sceneId: 'harness-framing',
    heading: 'Agent = Model + Harness',
    body: 'The cleanest definition in the field comes from the practitioners building these systems: every coding agent is a model nested inside a harness. The model decides the next move. The harness determines what is visible, actionable, permitted, persisted, and verifiable. If you are not the model, you are the harness. This is the machine.',
    lensMode: 'product',
  },
  {
    id: 'harness-subsystems',
    chapterId: 'harness-reveal',
    sceneId: 'harness-framing',
    heading: 'Five subsystems, one operating layer',
    body: 'A well-designed harness has five practical subsystems: instructions (what the agent should know), tools (what it can do), environment (where it operates), state (what it remembers), and feedback (how it knows whether it succeeded). Together, these turn a raw model into a system that can inspect, modify, verify, and recover.',
    lensMode: 'product',
  },
  {
    id: 'loop-intro',
    chapterId: 'flight-recorder',
    sceneId: 'first-loop',
    heading: 'The gather → act → observe → verify loop',
    body: 'At its core, a coding agent repeats a deceptively simple loop: gather context from the environment, choose the next useful action, execute it through tools, inspect what happened, and decide whether to continue or stop. The loop itself is small. Everything else — context shaping, tool dispatch, permission checks, recovery, memory, observability — belongs to the harness around it.',
    lensMode: 'product',
  },
  {
    id: 'loop-request-intake',
    chapterId: 'flight-recorder',
    sceneId: 'first-loop',
    heading: 'Step 1: The request enters the system',
    body: 'The user asks the agent to build a landing page. The harness receives this request and begins framing the task. It loads system instructions, orients to the repository, and assembles the initial context window — a working set of relevant files, conventions, and guardrails the model will need before it takes its first action.',
    lensMode: 'product',
  },
  {
    id: 'tool-invocation-intro',
    chapterId: 'flight-recorder',
    sceneId: 'tool-invocation',
    heading: 'Tools are the agent\'s action vocabulary',
    body: 'Without tools, a model can only produce text. With tools, it can inspect files, edit artifacts, run commands, search code, and verify outcomes against the environment. The harness does not merely give the model more power — it defines which actions are expressible, which are safe, which are observable, and which produce useful evidence for the next turn.',
    lensMode: 'product',
  },
  {
    id: 'tool-dispatch',
    chapterId: 'flight-recorder',
    sceneId: 'tool-invocation',
    heading: 'How a tool call actually works',
    body: 'When the model decides to act, it emits a structured tool-use request — say, read_file on index.html. The harness intercepts this request, validates it against registered tool schemas, checks permissions and sandboxing rules, and only then dispatches the real file read. The result returns as a structured observation that feeds directly into the next loop iteration.',
    lensMode: 'product',
  },
  {
    id: 'permission-intro',
    chapterId: 'flight-recorder',
    sceneId: 'permission-gate',
    heading: 'Agency with boundaries',
    body: 'Coding agents are powerful precisely because they can touch real systems — but that power requires control. Every tool invocation passes through a permission pipeline: deny-first rules, approval modes, sandboxing, and policy checks. The goal is not to block everything, but to make the boundary visible and deliberate.',
    lensMode: 'product',
  },
  {
    id: 'permission-approval',
    chapterId: 'flight-recorder',
    sceneId: 'permission-gate',
    heading: 'Why approval alone is not enough',
    body: 'In practice, human approval dialogs degrade quickly: when every prompt looks similar, users stop reading and just click approve. That is why mature harnesses layer multiple control mechanisms — sandboxes, checkpoints, deny-first defaults, and programmable hooks — so the system stays steerable even when attention flags.',
    lensMode: 'product',
  },
  {
    id: 'context-intro',
    chapterId: 'flight-recorder',
    sceneId: 'context-pressure',
    heading: 'The context window is a scarce resource',
    body: 'Every file read, every tool output, every planning step, and every instruction takes up space in the context window. As the agent works, the window fills with system prompts, user intent, tool results, plans, and partial outputs. The model must reason from a growing, increasingly crowded working set — and that crowding has real consequences for performance.',
    lensMode: 'product',
  },
  {
    id: 'context-pressure-body',
    chapterId: 'flight-recorder',
    sceneId: 'context-pressure',
    heading: 'When the window gets crowded',
    body: 'Near capacity, context rot sets in. Attention diffuses across stale or irrelevant content. The model may rush decisions prematurely, skip verification steps, or lose track of earlier constraints. This is not a model weakness — it is a systems constraint. The harness must manage the window deliberately.',
    lensMode: 'product',
  },
  {
    id: 'compaction-intro',
    chapterId: 'flight-recorder',
    sceneId: 'compaction',
    heading: 'Forgetting without failing',
    body: 'When the context window approaches its limit, the harness performs compaction: it summarizes the conversation so far into a condensed representation, drops stale frames, and frees up space for the next phase of work. Compaction is lossy by design. The art is preserving what matters — the current task, the constraints, the key decisions — while discarding what has already been acted on.',
    lensMode: 'product',
  },
  {
    id: 'compaction-tradeoff',
    chapterId: 'flight-recorder',
    sceneId: 'compaction',
    heading: 'The compaction tradeoff',
    body: 'A good compaction preserves continuity. A bad compaction loses the thread — it summarizes the wrong information, drops a constraint that was still load-bearing, or flattens nuance into a misleading summary. The harness must decide what to keep, what to compress, and what to re-inject from durable storage after compaction clears the window.',
    lensMode: 'product',
  },
  {
    id: 'memory-intro',
    chapterId: 'flight-recorder',
    sceneId: 'memory-retrieval',
    heading: 'Memory is not the same as compaction',
    body: 'Compaction manages transient conversation within a single run. Memory is durable information that outlives any one session: saved notes, project conventions, learned preferences, decision logs, and continuity artifacts. When a new session starts, the harness retrieves memory to avoid expensive cold starts.',
    lensMode: 'product',
  },
  {
    id: 'memory-retrieval-body',
    chapterId: 'flight-recorder',
    sceneId: 'memory-retrieval',
    heading: 'How memory shapes the next session',
    body: 'When a fresh session begins, the harness loads bootstrapping context: routing files, project structure, key decisions, and recent progress. The retrieved memory becomes part of the opening context window, giving the new session a running start. Without it, every session rediscovers the same facts at the cost of time, tokens, and correctness.',
    lensMode: 'product',
  },
  {
    id: 'failure-permission-intro',
    chapterId: 'flight-recorder',
    sceneId: 'failure-permission-blocked',
    heading: 'When the gate says no',
    body: 'The agent proposes a command — maybe something risky, like deleting a file or pushing to a remote. The permission pipeline intercepts it. A deny-first rule fires, or the approval threshold is not met, or the sandbox policy blocks execution. The tool does not run. The agent must now recover: explain what was blocked, propose an alternative, and continue. This is not failure — it is the harness working as designed.',
    lensMode: 'product',
  },
  {
    id: 'failure-permission-recovery',
    chapterId: 'flight-recorder',
    sceneId: 'failure-permission-blocked',
    heading: 'Recovery after a blocked action',
    body: 'A healthy agent does not crash or loop when blocked. It reads the denial reason, re-plans, and tries a different path. The harness helps by returning structured permission results — not just "denied" but why, and what would need to change. Good harness design treats blocked actions as information, not as errors.',
    lensMode: 'product',
  },
  {
    id: 'failure-tool-intro',
    chapterId: 'flight-recorder',
    sceneId: 'failure-tool-failure',
    heading: 'When a tool call fails',
    body: 'The agent invokes a tool — say, running a build command — and the command returns a non-zero exit code. The tool itself succeeded at executing, but the result is a failure. Now the agent must read the error output, diagnose the cause, and decide: retry with adjustments, try a different approach, or escalate. This is the point where many weak agents spiral, repeating the same failing command without learning.',
    lensMode: 'product',
  },
  {
    id: 'failure-tool-recovery',
    chapterId: 'flight-recorder',
    sceneId: 'failure-tool-failure',
    heading: 'The diagnosis-recovery loop',
    body: 'Strong agent systems make tool failures recoverable. They preserve the error output, inject it back into context so the model can reason about it, and provide verification tools (linters, type checkers, test runners) that convert ambiguous failure into concrete, actionable signal. The harness decides whether a failure is terminal, retryable, or requires a strategy change — and that decision is what separates a brittle agent from a durable one.',
    lensMode: 'product',
  },
  {
    id: 'loop-harness',
    chapterId: 'flight-recorder',
    sceneId: 'first-loop',
    heading: 'The gather → act → observe → verify loop',
    body: 'The agent loop is the irreducible runtime: gather context, choose action, execute through tools, inspect results, repeat. The harness owns every decision around this loop — context shaping, tool dispatch, permission checks, sandboxing, compaction policy, and recovery strategy. The loop is simple; the harness around it is where engineering maturity lives.',
    lensMode: 'harness',
  },
  {
    id: 'tool-harness',
    chapterId: 'flight-recorder',
    sceneId: 'tool-invocation',
    heading: 'Tool dispatch architecture',
    body: 'When the model emits a tool_use block, the harness intercepts it, validates the payload against registered tool schemas, checks permissions and sandbox rules, routes to the correct executor, captures stdout/stderr and exit codes, formats a structured observation, and injects it back into the conversation transcript. Each of these steps is a harness design decision with durability consequences.',
    lensMode: 'harness',
  },
  {
    id: 'permission-harness',
    chapterId: 'flight-recorder',
    sceneId: 'permission-gate',
    heading: 'The authorization pipeline',
    body: 'The permission pipeline is a layered sequence: deny-first rules, classifier checks, approval thresholds, sandbox boundaries, and post-execution audit hooks. The design lesson from production data is that approval dialogs alone are insufficient — 93% are approved without meaningful review. Real control lives in deny-first defaults, programmable hooks, and checkpoint reversibility.',
    lensMode: 'harness',
  },
  {
    id: 'context-harness',
    chapterId: 'flight-recorder',
    sceneId: 'context-pressure',
    heading: 'Context engineering strategy',
    body: 'Every byte in the context window is a resource allocation decision. The harness must decide what to load at startup, when to compact, what survives compaction, when to re-inject from durable storage, and when to offload work to an isolated subagent. Context engineering — not model size — is the primary lever for agent reliability at scale.',
    lensMode: 'harness',
  },
  {
    id: 'compaction-harness',
    chapterId: 'flight-recorder',
    sceneId: 'compaction',
    heading: 'Compaction as a systems operation',
    body: 'Compaction is a lossy summarization that condenses conversation history into a smaller representation. The harness must decide the compaction trigger (token budget threshold), the compaction strategy (summary vs. prune vs. re-inject), and what to preserve: current task intent, key decisions, constraints still in force, and the path forward. A bad compaction loses the thread; a good compaction preserves continuity.',
    lensMode: 'harness',
  },
  {
    id: 'memory-harness',
    chapterId: 'flight-recorder',
    sceneId: 'memory-retrieval',
    heading: 'Memory architecture and retrieval strategy',
    body: 'Memory is durable state that outlives any single session: saved notes, project conventions, decision logs, continuity artifacts. The harness must decide what to store, how to index it, when to retrieve it, and how to present it in the opening context — so a fresh session starts informed rather than cold.',
    lensMode: 'harness',
  },
  {
    id: 'failure-permission-harness',
    chapterId: 'flight-recorder',
    sceneId: 'failure-permission-blocked',
    heading: 'Designing recoverable permission boundaries',
    body: 'When a deny-first rule fires, the harness must return structured information — not just "denied" but why, and what would need to change. The agent reads this as input for its next plan. Harness design here is about making blocks informative enough that the agent can self-correct rather than loop.',
    lensMode: 'harness',
  },
  {
    id: 'failure-tool-harness',
    chapterId: 'flight-recorder',
    sceneId: 'failure-tool-failure',
    heading: 'Building recovery into the tool layer',
    body: 'Tool failure handling is a harness-level concern. The harness captures exit codes and error streams, formats them as structured observations, and preserves them in context so the model can reason. Verification tools (linters, type checkers, test runners) convert ambiguous failure into actionable signal. Recovery policy — retry, replan, escalate — is a harness decision.',
    lensMode: 'harness',
  },
];
