import type { ContentBlock } from './scene';

export const INTRO_CONTENT: ContentBlock[] = [
  {
    id: 'hook-heading',
    chapterId: 'hook',
    sceneId: 'teaser-cross-section',
    heading: 'What happens when you ask a coding agent to build something?',
    body: 'You type a plain-English request — "build me a landing page" — and press enter. The model begins. But what actually happens between that request and the finished page? The answer is not "the model figures it out." The answer is a system — a harness — that turns model intelligence into real, verifiable work.',
    lensMode: 'product',
  },
  {
    id: 'hook-body',
    chapterId: 'hook',
    sceneId: 'teaser-cross-section',
    heading: 'The mental model shift',
    body: 'Most of us imagine a coding agent as a chatbot with better prose. A smart text-in, smart-text-out machine. That model is wrong. A coding agent is a system that reasons, acts through tools, observes results, and continues — not a single response, but a work loop that runs until the job is done.',
    lensMode: 'product',
  },
  {
    id: 'illusion-heading',
    chapterId: 'illusion-break',
    sceneId: 'model-only-misconception',
    heading: 'The model alone cannot do this job',
    body: 'A language model on its own can produce text. It can describe a landing page. It can write HTML. But it cannot open a file, read your existing codebase, run a test, or check whether its output actually works. The model is a reasoning engine. Without a harness around it, it is blind, handless, and stateless.',
    lensMode: 'product',
  },
  {
    id: 'illusion-contrast',
    chapterId: 'illusion-break',
    sceneId: 'model-only-misconception',
    heading: 'Model-only vs. harnessed agent',
    body: 'Without a harness, every request starts from scratch. The model cannot persist state, browse project structure, run commands, or validate outcomes. A harness changes this: it gives the model eyes (file reads), hands (tool execution), memory (session state), and boundaries (permissions). The difference is the difference between a brilliant advisor and a capable colleague.',
    lensMode: 'product',
  },
  {
    id: 'harness-heading',
    chapterId: 'harness-reveal',
    sceneId: 'harness-framing',
    heading: 'Agent = Model + Harness',
    body: 'The cleanest definition in the field comes from the practitioners building these systems: every coding agent is a model nested inside a harness. The model decides the next move. The harness determines what is visible, actionable, permitted, persisted, and verifiable. If you are not the model, you are the harness. This is the machine.',
    lensMode: 'product',
  },
  {
    id: 'harness-subsystems',
    chapterId: 'harness-reveal',
    sceneId: 'harness-framing',
    heading: 'Five subsystems, one operating layer',
    body: 'A well-designed harness has five practical subsystems: instructions (what the agent should know), tools (what it can do), environment (where it operates), state (what it remembers), and feedback (how it knows whether it succeeded). Together, these turn a raw model into a system that can inspect, modify, verify, and recover.',
    lensMode: 'product',
  },
  {
    id: 'loop-intro',
    chapterId: 'flight-recorder',
    sceneId: 'first-loop',
    heading: 'The gather → act → observe → verify loop',
    body: 'At its core, a coding agent repeats a deceptively simple loop: gather context from the environment, choose the next useful action, execute it through tools, inspect what happened, and decide whether to continue or stop. The loop itself is small. Everything else — context shaping, tool dispatch, permission checks, recovery, memory, observability — belongs to the harness around it.',
    lensMode: 'product',
  },
  {
    id: 'loop-request-intake',
    chapterId: 'flight-recorder',
    sceneId: 'first-loop',
    heading: 'Step 1: The request enters the system',
    body: 'The user asks the agent to build a landing page. The harness receives this request and begins framing the task. It loads system instructions, orients to the repository, and assembles the initial context window — a working set of relevant files, conventions, and guardrails the model will need before it takes its first action.',
    lensMode: 'product',
  },
  {
    id: 'tool-invocation-intro',
    chapterId: 'flight-recorder',
    sceneId: 'tool-invocation',
    heading: 'Tools are the agent\'s action vocabulary',
    body: 'Without tools, a model can only produce text. With tools, it can inspect files, edit artifacts, run commands, search code, and verify outcomes against the environment. The harness does not merely give the model more power — it defines which actions are expressible, which are safe, which are observable, and which produce useful evidence for the next turn.',
    lensMode: 'product',
  },
  {
    id: 'tool-dispatch',
    chapterId: 'flight-recorder',
    sceneId: 'tool-invocation',
    heading: 'How a tool call actually works',
    body: 'When the model decides to act, it emits a structured tool-use request — say, read_file on index.html. The harness intercepts this request, validates it against registered tool schemas, checks permissions and sandboxing rules, and only then dispatches the real file read. The result returns as a structured observation that feeds directly into the next loop iteration.',
    lensMode: 'product',
  },
  {
    id: 'permission-intro',
    chapterId: 'flight-recorder',
    sceneId: 'permission-gate',
    heading: 'Agency with boundaries',
    body: 'Coding agents are powerful precisely because they can touch real systems — but that power requires control. Every tool invocation passes through a permission pipeline: deny-first rules, approval modes, sandboxing, and policy checks. The goal is not to block everything, but to make the boundary visible and deliberate.',
    lensMode: 'product',
  },
  {
    id: 'permission-approval',
    chapterId: 'flight-recorder',
    sceneId: 'permission-gate',
    heading: 'Why approval alone is not enough',
    body: 'In practice, human approval dialogs degrade quickly: when every prompt looks similar, users stop reading and just click approve. That is why mature harnesses layer multiple control mechanisms — sandboxes, checkpoints, deny-first defaults, and programmable hooks — so the system stays steerable even when attention flags.',
    lensMode: 'product',
  },
  {
    id: 'context-intro',
    chapterId: 'flight-recorder',
    sceneId: 'context-pressure',
    heading: 'The context window is a scarce resource',
    body: 'Every file read, every tool output, every planning step, and every instruction takes up space in the context window. As the agent works, the window fills with system prompts, user intent, tool results, plans, and partial outputs. The model must reason from a growing, increasingly crowded working set — and that crowding has real consequences for performance.',
    lensMode: 'product',
  },
  {
    id: 'context-pressure-body',
    chapterId: 'flight-recorder',
    sceneId: 'context-pressure',
    heading: 'When the window gets crowded',
    body: 'Near capacity, context rot sets in. Attention diffuses across stale or irrelevant content. The model may rush decisions prematurely, skip verification steps, or lose track of earlier constraints. This is not a model weakness — it is a systems constraint. The harness must manage the window deliberately.',
    lensMode: 'product',
  },
  {
    id: 'compaction-intro',
    chapterId: 'flight-recorder',
    sceneId: 'compaction',
    heading: 'Forgetting without failing',
    body: 'When the context window approaches its limit, the harness performs compaction: it summarizes the conversation so far into a condensed representation, drops stale frames, and frees up space for the next phase of work. Compaction is lossy by design. The art is preserving what matters — the current task, the constraints, the key decisions — while discarding what has already been acted on.',
    lensMode: 'product',
  },
  {
    id: 'compaction-tradeoff',
    chapterId: 'flight-recorder',
    sceneId: 'compaction',
    heading: 'The compaction tradeoff',
    body: 'A good compaction preserves continuity. A bad compaction loses the thread — it summarizes the wrong information, drops a constraint that was still load-bearing, or flattens nuance into a misleading summary. The harness must decide what to keep, what to compress, and what to re-inject from durable storage after compaction clears the window.',
    lensMode: 'product',
  },
  {
    id: 'memory-intro',
    chapterId: 'flight-recorder',
    sceneId: 'memory-retrieval',
    heading: 'Memory is not the same as compaction',
    body: 'Compaction manages transient conversation within a single run. Memory is durable information that outlives any one session: saved notes, project conventions, learned preferences, decision logs, and continuity artifacts. When a new session starts, the harness retrieves memory to avoid expensive cold starts.',
    lensMode: 'product',
  },
  {
    id: 'memory-retrieval-body',
    chapterId: 'flight-recorder',
    sceneId: 'memory-retrieval',
    heading: 'How memory shapes the next session',
    body: 'When a fresh session begins, the harness loads bootstrapping context: routing files, project structure, key decisions, and recent progress. The retrieved memory becomes part of the opening context window, giving the new session a running start. Without it, every session rediscovers the same facts at the cost of time, tokens, and correctness.',
    lensMode: 'product',
  },
];
