export function HarnessFramingScene() {
  return (
    <svg
      viewBox="0 0 440 360"
      xmlns="http://www.w3.org/2000/svg"
      style={{ width: '100%', maxWidth: 440 }}
      role="img"
      aria-label="Full harness framing diagram showing model inside harness with tools, context, permissions, and memory"
    >
      <rect
        x={20}
        y={20}
        width={400}
        height={320}
        rx={14}
        fill="var(--color-harness)"
        fillOpacity={0.06}
        stroke="var(--color-harness)"
        strokeWidth={2}
      />
      <text
        x={35}
        y={46}
        fontFamily="var(--font-ui)"
        fontSize={14}
        fontWeight={700}
        fill="var(--color-harness)"
        textAnchor="start"
      >
        HARNESS
      </text>
      <text
        x={35}
        y={62}
        fontFamily="var(--font-mono)"
        fontSize={10}
        fill="var(--color-harness)"
        textAnchor="start"
        fillOpacity={0.8}
      >
        every non-model system component
      </text>

      <rect
        x={40}
        y={80}
        width={165}
        height={108}
        rx={8}
        fill="var(--color-paper)"
        stroke="var(--color-metal)"
        strokeWidth={1}
      />
      <text
        x={50}
        y={98}
        fontFamily="var(--font-mono)"
        fontSize={9}
        fill="var(--color-memory)"
        fontWeight={600}
      >
        Context Window
      </text>
      <rect
        x={50}
        y={105}
        width={145}
        height={18}
        rx={3}
        fill="var(--color-harness)"
        fillOpacity={0.12}
        stroke="var(--color-harness)"
        strokeWidth={0.5}
      />
      <text
        x={56}
        y={117}
        fontFamily="var(--font-mono)"
        fontSize={9}
        fill="var(--color-harness)"
      >
        System instructions
      </text>
      <rect
        x={50}
        y={127}
        width={135}
        height={18}
        rx={3}
        fill="var(--color-human)"
        fillOpacity={0.12}
        stroke="var(--color-human)"
        strokeWidth={0.5}
      />
      <text
        x={56}
        y={139}
        fontFamily="var(--font-mono)"
        fontSize={9}
        fill="var(--color-human)"
      >
        User: build landing page
      </text>
      <rect
        x={50}
        y={149}
        width={125}
        height={18}
        rx={3}
        fill="var(--color-model)"
        fillOpacity={0.12}
        stroke="var(--color-model)"
        strokeWidth={0.5}
      />
      <text
        x={56}
        y={161}
        fontFamily="var(--font-mono)"
        fontSize={9}
        fill="var(--color-model)"
      >
        Plan: scaffold → verify
      </text>

      <rect
        x={145}
        y={215}
        width={110}
        height={56}
        rx={10}
        fill="var(--color-model)"
        fillOpacity={0.12}
        stroke="var(--color-model)"
        strokeWidth={1.8}
      />
      <text
        x={200}
        y={240}
        fontFamily="var(--font-mono)"
        fontSize={12}
        fontWeight={600}
        fill="var(--color-model)"
        textAnchor="middle"
      >
        MODEL
      </text>
      <text
        x={200}
        y={258}
        fontFamily="var(--font-mono)"
        fontSize={10}
        fill="var(--color-model)"
        textAnchor="middle"
        fillOpacity={0.7}
      >
        reasoning engine
      </text>

      <rect
        x={310}
        y={85}
        width={95}
        height={42}
        rx={6}
        fill="var(--color-tool)"
        fillOpacity={0.12}
        stroke="var(--color-tool)"
        strokeWidth={1.5}
      />
      <text
        x={357}
        y={103}
        fontFamily="var(--font-mono)"
        fontSize={11}
        fontWeight={600}
        fill="var(--color-tool)"
        textAnchor="middle"
      >
        Tools
      </text>
      <text
        x={357}
        y={119}
        fontFamily="var(--font-mono)"
        fontSize={9}
        fill="var(--color-tool)"
        textAnchor="middle"
        fillOpacity={0.7}
      >
        read, write, run
      </text>

      <line
        x1={255}
        y1={230}
        x2={310}
        y2={106}
        stroke="var(--color-tool)"
        strokeWidth={1.5}
        markerEnd="url(#arrow-harness)"
      />

      <defs>
        <marker
          id="arrow-harness"
          viewBox="0 0 10 7"
          refX={9}
          refY={3.5}
          markerWidth={7}
          markerHeight={5}
          orient="auto"
        >
          <polygon points="0 0, 10 3.5, 0 7" fill="var(--color-tool)" />
        </marker>
      </defs>

      <rect
        x={310}
        y={150}
        width={95}
        height={42}
        rx={6}
        fill="var(--color-warning)"
        fillOpacity={0.08}
        stroke="var(--color-warning)"
        strokeWidth={1.2}
      />
      <text
        x={357}
        y={168}
        fontFamily="var(--font-mono)"
        fontSize={11}
        fontWeight={600}
        fill="var(--color-warning)"
        textAnchor="middle"
      >
        Permissions
      </text>
      <text
        x={357}
        y={184}
        fontFamily="var(--font-mono)"
        fontSize={9}
        fill="var(--color-warning)"
        textAnchor="middle"
        fillOpacity={0.7}
      >
        gate &amp; approve
      </text>

      <line
        x1={200}
        y1={271}
        x2={200}
        y2={285}
        stroke="var(--color-memory)"
        strokeWidth={1.5}
      />
      <rect
        x={145}
        y={285}
        width={110}
        height={38}
        rx={6}
        fill="var(--color-memory)"
        fillOpacity={0.12}
        stroke="var(--color-memory)"
        strokeWidth={1.2}
      />
      <text
        x={200}
        y={303}
        fontFamily="var(--font-mono)"
        fontSize={11}
        fontWeight={600}
        fill="var(--color-memory)"
        textAnchor="middle"
      >
        Memory
      </text>
      <text
        x={200}
        y={318}
        fontFamily="var(--font-mono)"
        fontSize={9}
        fill="var(--color-memory)"
        textAnchor="middle"
        fillOpacity={0.7}
      >
        state &amp; retrieval
      </text>
    </svg>
  );
}
